#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

dest=$1

if [ -z "$dest" ]; then
  echo "usage: $0 <path/to/volume>"
  exit 1
fi

source "$(dirname $0)/common.sh"

payload=`cat`
bucket=$(get_bucket)
prefix=$(echo "$payload" | jq -r '.params.prefix // ""')
options=$(echo "$payload" | jq -r '.params.options // [] | join(" ")')
skip_download=$(echo "$payload" | jq -r '.params.skip_download // false')

export_aws_vars

if [ "$skip_download" = "true" ]; then
  echo "Skipping download from S3"
else
  echo "Downloading from S3..."
  eval aws s3 sync "s3://$bucket/$prefix" $dest $options
  echo "Done."
fi

emit_version
